// <auto-generated />
using System;
using EduConnect.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EduConnect.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<Guid>("EnrolledId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnrollmentsId")
                        .HasColumnType("uuid");

                    b.HasKey("EnrolledId", "EnrollmentsId");

                    b.HasIndex("EnrollmentsId");

                    b.ToTable("CourseStudent", (string)null);
                });

            modelBuilder.Entity("EduConnect.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedFacultyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CreditHours")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedFacultyId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("EduConnect.Models.GradeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CreditHours")
                        .HasColumnType("integer");

                    b.Property<int>("Marks")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("EduConnect.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("EduConnect.Models.Admin", b =>
                {
                    b.HasBaseType("EduConnect.Models.Person");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("EduConnect.Models.Faculty", b =>
                {
                    b.HasBaseType("EduConnect.Models.Person");

                    b.ToTable("Faculty", (string)null);
                });

            modelBuilder.Entity("EduConnect.Models.Student", b =>
                {
                    b.HasBaseType("EduConnect.Models.Person");

                    b.Property<decimal>("CGPA")
                        .HasColumnType("numeric");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("EduConnect.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("EnrolledId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduConnect.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("EnrollmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EduConnect.Models.Course", b =>
                {
                    b.HasOne("EduConnect.Models.Faculty", null)
                        .WithMany("AssignedCourses")
                        .HasForeignKey("AssignedFacultyId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("EduConnect.Models.GradeRecord", b =>
                {
                    b.HasOne("EduConnect.Models.Student", null)
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EduConnect.Models.Faculty", b =>
                {
                    b.Navigation("AssignedCourses");
                });

            modelBuilder.Entity("EduConnect.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
